---
# Kubernetes version
k8s_version: "1.29"
k8s_version_full: "1.29.0-1.1"
containerd_version: "1.7.*"

# Pod & service CIDRs
pod_cidr: "10.244.0.0/16"
service_cidr: "10.96.0.0/12"

# HAProxy / VIP
lb_ip: "10.211.55.10"
lb_port: 6443

# Flannel CNI manifest
flannel_manifest: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"
