apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: finpulse
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/krasteki/finpulse-app.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: finpulse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
